# spring.application.name=backend

# server.port=8081

# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# spring.h2.console.enabled=true
spring.datasource.url=postgresql://javabackend1_user:GZs02r093CoyaV489nocsJQ4kbVZvPyO@dpg-d6kgrc5m5p6s73dqiil0-a.oregon-postgres.render.com/javabackend1
spring.datasource.username=javabackend1_user
spring.datasource.password=GZs02r093CoyaV489nocsJQ4kbVZvPyO

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true